name: DavidLoosen
favicon: null
layout_spectrum: 0.8273771547246724
typography_spectrum: 0.4897101470269263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5243503348901868
  lightness: 0.9446881997864693
  saturation: 0.8488718795124441
  rhythmicContrast: 0.23624722263775766
purpose: []
