name: DavidLoosen
favicon: null
layout_spectrum: 0.57958
typography_spectrum: 0.4897101470269263
title: David R. Loosen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#39a9dc'
    - '#ffffff'
    - '#e0f1f9'
    - '#91cfeb'
    - '#b3def1'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.23624722263775766
purpose: []
